services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    volumes:
      - type: bind
        source: ./config/mosquitto
        target: /mosquitto/config/
      - type: bind
        source: ./volumes/mosquitto/log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

volumes:
  data:
    name: "mqtt-broker-data"